// Event types published to the audit log
export const EVENTS = {
  LTI_LAUNCH_RECEIVED:     'LTI_LAUNCH_RECEIVED',
  LTI_LAUNCH_VALIDATED:    'LTI_LAUNCH_VALIDATED',
  LTI_LAUNCH_FAILED:       'LTI_LAUNCH_FAILED',
  SESSION_CREATED:         'SESSION_CREATED',
  SESSION_RESUMED:         'SESSION_RESUMED',
  SESSION_EXPIRED:         'SESSION_EXPIRED',
  SAP_USER_ASSIGNED:       'SAP_USER_ASSIGNED',
  SAP_USER_RELEASED:       'SAP_USER_RELEASED',
  SAP_VERIFICATION_START:  'SAP_VERIFICATION_START',
  SAP_VERIFICATION_PASS:   'SAP_VERIFICATION_PASS',
  SAP_VERIFICATION_FAIL:   'SAP_VERIFICATION_FAIL',
  SAP_VERIFICATION_ERROR:  'SAP_VERIFICATION_ERROR',
  CHECKIN_COMPLETED:       'CHECKIN_COMPLETED',
  ACTIVITY_SUBMITTED:      'ACTIVITY_SUBMITTED',
  CHECKOUT_STARTED:        'CHECKOUT_STARTED',
  CHECKOUT_TURN:           'CHECKOUT_TURN',
  ASSESSMENT_COMPLETE:     'ASSESSMENT_COMPLETE',
  SESSION_COMPLETED:       'SESSION_COMPLETED',
  GRADE_POSTED:            'GRADE_POSTED',
  GRADE_POST_FAILED:       'GRADE_POST_FAILED',
  BADGE_ISSUED:            'BADGE_ISSUED',
  BADGE_ISSUE_FAILED:      'BADGE_ISSUE_FAILED',
  RETRY_CREATED:           'RETRY_CREATED',
} as const;

export type EventType = typeof EVENTS[keyof typeof EVENTS];
